Big update
data-science-ucsb/ds-website-new pull request #2
Opened 2024-03-17 01:03 UTC by cboiteux2765

Added long description and event expanded image after clicking card (CSS still in progress), solved card alignment issue for board members, updated club info such as tech dev position names and FAQs

2024-04-10 04:28 UTC, WinbertZhang requested changes
For the event cards, the flip side images sometimes take a while to load and the animation after clicking on the event can be clunky. If possible we can try to instead have each card link to a separate page that contains the full description instead

Looks like register is currently down, let’s keep it out of the pull request for now until the page is up

2024-07-30 05:23 UTC, BLimmie commented on data/alumni.ts
> +    job: "Software Engineer @ Amazon",
Should be Palantir

2024-07-30 05:24 UTC, BLimmie commented
Maybe something to look into for a future PR: pulling directly from Linkedin the latest job from each alumni so this doesn't need manual changing

2024-07-31 02:49 UTC, WinbertZhang commented
> Maybe something to look into for a future PR: pulling directly from Linkedin the latest job from each alumni so this doesn't need manual changing

Moved to Issue #4!

2024-07-31 02:50 UTC, WinbertZhang approved these changes
LGTM

2024-07-31 02:51 UTC, merged